name: EAS Build

on:
  push:
    branches: [ main ]

env:
  EAS_BUILD_NO_EXPO_GO_WARNING: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci

      - name: Install EAS CLI
        run: |
          npm install -g eas-cli

      - name: EAS Build (Android production)
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: |
          eas build --platform android --profile production --non-interactive
